#!/bin/sh
docker buildx build --platform linux/amd64 --provenance=false -t watermark-app-lambda:latest .
docker tag watermark-app-lambda:latest 000000000000.dkr.ecr.us-east-1.amazonaws.com/watermark-document:latest
